infoSystem/apps/persons/urls.py
from django.urls import path
from . import views

app_name = 'persons'
urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),
    path('create/', views.create_page, name='create_page'),
    path('add/', views.create, name='create')
]

infoSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persons.urls')),
    path('accounts/', include('allauth.urls'))
]

infoSystem/apps/persons/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField("Имя человека", max_length=100)
    surmane = models.CharField("Фамилия человека", max_length=100)
    birthdate = models.DateField("Дата рождения")
    image_url = models.CharField("Ссылка на фото", max_length=300)

    def __str__(self):
        return self.name + ' ' + self.surmane

infoSystem/apps/persons/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Person

def index(request):
    user_name = 'Django'
    user_age = 21
    persons = Person.objects.all
    return render(request, 'person/persons.html', { 'name': user_name, 'age' : user_age, 'persons' : persons })

def test(request):
    return render(request, 'person/test.html')

def create_page(request):
    return render(request, 'person/create.html')

def create(request):
    Person.objects.create(
        name = request.POST['name'],
        surmane = request.POST['surmane'],
        birthdate = request.POST['birthdate'],
        image_url = request.POST['image_url']
    )
    return HttpResponseRedirect( reverse('persons:index'))

infoSystem/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <title>
            {% block title %} Info System {% endblock %}
        </title>
    </head>
    <div>
        {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'persons:index' %}">Navbar</a>
            {% if user.is_authenticated%}
            {{user.username}}
        {% else %}
            <p>Вы не авторизованы</p>
        {% endif%}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'persons:test' %}">test <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
              </ul>
              
            </div>
          </nav>
        {% endblock %}
    </div>
    <body>
        <div class="container">
        {% block content %}{% endblock %}
        </div>
    </body>
</html>

infoSystem/templates/person/create.html
{% extends 'base.html' %}

{% block title %} Create Person {% endblock %}

{% block content %}
<h2> СОЗДАНИЕ ЧЕЛОВЕКА </h2>
<form action="{% url 'persons:create' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="form-control-label">Имя человека</label>
        <input type="text" required name="name" class="form-control" placeholder="Введите имя">
    </div>
    <div class="form-group">
        <label for="surmane" class="form-control-label">Фамилия</label>
        <input type="text" required name="surmane" class="form-control" placeholder="Введите фамилию">
    </div>
    <div class="form-group">
        <label for="birthdate" class="form-control-label">Дата рождения</label>
        <input type="date" required name="birthdate" class="form-control">
    </div>
    <div class="form-group">
        <label for="image_url" class="form-control-label">Ссылка на фото</label>
        <input type="text" required name="image_url" class="form-control" placeholder="Вставьте ссылку на фото">
    </div>
    <button type="submit" class="btn btn-primary">Сохнанить</button>
</form>
{% endblock%}

infoSystem/templates/person/persons.html
{% extends 'base.html' %}

{% block title %} Persons {% endblock %}

{% block content%}
    <h2>ТУТ ЛЮДИ-123</h2>
    <div>
        <h3>
            {{name}} : {{age}}
        </h3>
        <div>
            <form action="{% url 'persons:create_page' %}" method="GET">
                <button type="submit"  class="btn btn-primary">Добавить человека</button>
            </form>
        </div>
    </div>
    <div>
        {% if persons %}
            <div class="row mb-2">
            {% for person in persons %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" style="height: 225px; width: 100%; display: block;" src="{{person.image_url}}" data-holder-rendered="true">
                            <div class="card-body">
                            <p class="card-text">{{person.name}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{person.surname}}</small>
                                <small class="text-muted">{{person.birthdate}}</small>
                            </div>
                            </div>
                        </div>
                    </div>
            {% endfor%}
            </div>
        {% else %}
        <div>
            Список людей пуст
        </div>
        {% endif %}
       
    </div>
{% endblock%}

infoSystem/templates/person/test.html
{% extends 'base.html' %}

{% block content %}
<h2>
    А ТУТ ТЕСТ ветки девелоп
</h2>
{% endblock%}